using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

// Extracts enum-name -> human-readable-display maps for the item "bane"/multiplier enums and
// writes them to a JSON file. Re-run whenever the game updates.
//
//   dotnet run                    # writes enum-labels.json next to the .sln
//   dotnet run --out=labels.json  # custom output path
//
// Game install path auto-detects the same way as tools/reflect; override with PANTHEON_DIR.
//
// Sources (see the block comments below for the why):
//   * EntityMultiplierType - the player-facing labels ("Physical Crit Damage") only exist as a
//     curated UI string block inside global-metadata.dat; there is no enum->string method in code.
//     We reconstruct them from naming rules + a fixed table for the irregular ones, then VALIDATE
//     every produced label against the live metadata and warn on any that no longer appears (that's
//     your signal the game changed the wording and the table below needs an update).
//   * EntityKind / EntityRace - displayed at runtime via native EntityKindExtensions.AsString /
//     EntityRaceExtensions.ToDescription, which we can't call offline. The spaced forms aren't stored
//     in metadata either, so these are GENERATED by splitting the enum name on camelCase boundaries
//     ("DarkMyr" -> "Dark Myr"). Flagged as generated; correct via the override tables if any differ.

Console.OutputEncoding = Encoding.UTF8;

var outPath = "enum-labels.json";
foreach (var a in args)
    if (a.StartsWith("--out=")) outPath = a["--out=".Length..];

var gameDir = Environment.GetEnvironmentVariable("PANTHEON_DIR")
    ?? DetectGameDir()
    ?? throw new Exception("Could not find Pantheon install. Set PANTHEON_DIR env var.");

// ── Load the three enums (name -> value) via offline reflection ──────────────

var il2cppDir = Path.Combine(gameDir, "MelonLoader", "Il2CppAssemblies");
var net6Dir   = Path.Combine(gameDir, "MelonLoader", "net6");
var runtimeDir = System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory();

var allDlls = Directory.GetFiles(il2cppDir, "*.dll")
    .Concat(Directory.GetFiles(net6Dir, "*.dll"))
    .Concat(Directory.GetFiles(runtimeDir, "*.dll"))
    .ToArray();

using var mlc = new MetadataLoadContext(new PathAssemblyResolver(allDlls));

var enumTypes = Directory.GetFiles(il2cppDir, "Il2Cpp*.dll")
    .Concat(new[] { Path.Combine(il2cppDir, "Assembly-CSharp.dll") })
    .Where(File.Exists)
    .SelectMany(path => { try { return mlc.LoadFromAssemblyPath(path).GetTypes(); } catch { return Array.Empty<Type>(); } })
    .Where(t => t.IsEnum)
    .ToArray();

// ── Metadata string index (for validating multiplier labels) ─────────────────

var metadataPath = Environment.GetEnvironmentVariable("PANTHEON_METADATA")
    ?? Path.Combine(gameDir, "Pantheon_Data", "il2cpp_data", "Metadata", "global-metadata.dat");
var metadataText = File.Exists(metadataPath)
    ? ExtractAsciiText(File.ReadAllBytes(metadataPath))
    : null;
if (metadataText == null)
    Console.Error.WriteLine($"WARNING: metadata not found at {metadataPath} - skipping label validation.");

// ── Build the map ────────────────────────────────────────────────────────────

// Only EntityMultiplierType is worth extracting: its player-facing labels ("Physical Crit Damage")
// exist as a curated string block in the metadata that we can validate against. Other enums' names
// are already display-ready or only differ by cosmetic spacing, so they aren't worth a lookup table.
var warnings = new List<string>();
var root = new JsonObject
{
    ["EntityMultiplierType"] = BuildMap("EntityMultiplierType", Labels.Multiplier, validate: true),
};

File.WriteAllText(outPath, root.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
Console.WriteLine($"Wrote {Path.GetFullPath(outPath)}");

if (warnings.Count > 0)
{
    Console.Error.WriteLine($"\n{warnings.Count} label(s) not found in metadata - the game may have changed the wording; update the tables in Program.cs:");
    foreach (var w in warnings) Console.Error.WriteLine($"  {w}");
}

return 0;

// ── Helpers ──────────────────────────────────────────────────────────────────

JsonObject BuildMap(string enumName, Func<string, string?> label, bool validate)
{
    var type = enumTypes.FirstOrDefault(t => t.Name == enumName)
        ?? throw new Exception($"Enum {enumName} not found in game assemblies.");

    var obj = new JsonObject();
    var labelled = 0;
    var fields = type.GetFields(BindingFlags.Public | BindingFlags.Static)
        .OrderBy(f => { try { return Convert.ToInt64(f.GetRawConstantValue()); } catch { return 0L; } });

    foreach (var f in fields)
    {
        if (f.Name == "Count") continue; // sentinel enum-length marker, not a real value
        var text = label(f.Name);
        if (text != null)
        {
            labelled++;
            if (validate && metadataText != null && !metadataText.Contains(text, StringComparison.Ordinal))
                warnings.Add($"{enumName}.{f.Name} => \"{text}\"");
        }
        obj[f.Name] = text; // null when the game gives no player-facing label
    }

    Console.WriteLine($"{enumName}: {labelled}/{obj.Count} values labelled");
    return obj;
}

// Flatten the metadata blob to text: printable ASCII kept as-is, everything else becomes '\n'. Labels
// are substring-searched against this (il2cpp glues a length-prefix byte onto stored strings, so an
// exact-match set would miss them).
static string ExtractAsciiText(byte[] data)
{
    var chars = new char[data.Length];
    for (var i = 0; i < data.Length; i++)
        chars[i] = data[i] is >= 0x20 and <= 0x7E ? (char)data[i] : '\n';
    return new string(chars);
}

static string? DetectGameDir()
{
    var candidates = new[]
    {
        @"D:\PantheonPTR\App",
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), @"Documents\My Games\Pantheon\App"),
        @"C:\Program Files (x86)\Steam\steamapps\common\Pantheon Rise of the Fallen",
    };
    return candidates.FirstOrDefault(d => Directory.Exists(Path.Combine(d, "MelonLoader")));
}

static class Labels
{
    // EntityMultiplierType -> UI label. Per-school entries are rule-derived so new schools/values are
    // picked up automatically; the irregular scalars come from a fixed table verified against metadata.
    public static string? Multiplier(string name)
    {
        if (Scalars.TryGetValue(name, out var scalar)) return scalar;

        Match m;
        if ((m = Regex.Match(name, $"^CritDamage({SchoolAlt})$")).Success) return $"{m.Groups[1].Value} Crit Damage";
        if ((m = Regex.Match(name, $"^In({SchoolAlt})CritChance$")).Success) return $"{m.Groups[1].Value} Crit Vulnerability";
        if ((m = Regex.Match(name, $"^Out({SchoolAlt})CritChance$")).Success) return $"{m.Groups[1].Value} Crit Chance";
        if (name == "CastingSpeedAll") return "Cast Speed";
        if ((m = Regex.Match(name, $"^CastingSpeed({SchoolAlt})$")).Success) return $"{m.Groups[1].Value} Cast Speed";
        if ((m = Regex.Match(name, $"^In({SchoolAlt})Damage$")).Success) return $"{m.Groups[1].Value} Damage Taken";
        if ((m = Regex.Match(name, $"^Out({SchoolAlt})Damage$")).Success) return $"{m.Groups[1].Value} Potency";

        return null; // internal/unused value with no player-facing label
    }

    const string SchoolAlt = "Physical|Magic|Fire|Cold|Poison|Disease|Shock|Curse|Divine|Chemical|Nature|Essence";

    // Irregular labels that don't follow the per-school pattern. Verified against global-metadata.dat.
    static readonly Dictionary<string, string> Scalars = new()
    {
        ["InDamage"] = "Damage Taken",
        ["OutDamage"] = "Damage",
        ["InPhysicalDamage"] = "Physical Damage Taken",
        ["OutPhysicalDamage"] = "Physical Damage Dealt",
        ["InSpellDamage"] = "Spell Damage Taken",
        ["InHealing"] = "Healing Received",
        ["OutHealing"] = "Healing Potency",
        ["OutCritHealing"] = "Critical Healing Potency",
        ["InDamageFromFront"] = "Damage Taken (front)",
        ["InDamageFromBehind"] = "Damage Taken (behind)",
        ["OutDamageFromFront"] = "Damage Dealt (front)",
        ["OutDamageFromBehind"] = "Damage Dealt (behind)",
        ["RoguePoisonProcChance"] = "Poison Volatility",
        ["CastingRange"] = "Cast Range",
        ["ExperienceMultiplier"] = "Experience Bonus",
        ["OutThreatGeneration"] = "Threat",
        ["InThreatGeneration"] = "Threat Taken",
        ["EnduranceRegen"] = "Endurance Recovery",
        ["BreathRegen"] = "Breath Recovery",
        ["OutTechniqueDamage"] = "Technique Damage Dealt",
        ["OutTechniqueCritChance"] = "Technique Crit Chance",
        ["OutTechniqueHitChance"] = "Technique Accuracy",
        ["OutAdditionalNonAutoAttackMeleeCritChance"] = "Melee Ability Crit Chance",
        ["OutAdditionalNonAutoAttackRangedCritChance"] = "Ranged Ability Crit Chance",
        ["InCrowdControlDuration"] = "Control Duration Vulnerability",
        ["OutCrowdControlDuration"] = "Control Duration Potency",
        ["OutAdditionalDamageOverTimeCritChance"] = "DoT Crit Chance",
        ["InAoeDamage"] = "AoE Vulnerability",
        ["OutAoeDamage"] = "AoE Damage Dealt",
        ["InRangedPhysicalDamage"] = "Ranged Damage Taken",
        ["OutRangedPhysicalDamage"] = "Ranged Damage Dealt",
        ["InRangedPhysicalCritChance"] = "Ranged Crit Vulnerability",
        ["OutRangedPhysicalCritChance"] = "Ranged Crit Chance",
        ["CritDamageRangedPhysical"] = "Ranged Crit Damage",
        ["RangedPhysicalAbilityCost"] = "Ranged Ability Cost",
    };
}
